#!/bin/sh

set -e

if [ -e /usr/lib/libqyoutube.so ]
    then
        rm /usr/lib/libqyoutube.so
fi

if [ -e /usr/lib/libqyoutube.so.1 ]
    then
        rm /usr/lib/libqyoutube.so.1
fi

if [ -e /usr/lib/libqyoutube.so.1.0 ]
    then
        rm /usr/lib/libqyoutube.so.1.0
fi

if [ -e /usr/lib/libqyoutube.so.1.0.0 ]
    then
        rm /usr/lib/libqyoutube.so.1.0.0
fi

if [ -h /usr/lib/qt4/imports/QYouTube ]
    then
        rm /usr/lib/qt4/imports/QYouTube
fi

exit 0
